Route1N_MapScripts::
	.byte 0


TrainerSchoolSign::
# 4 "data/maps/Route1N/scripts.pory"
	lock
# 5 "data/maps/Route1N/scripts.pory"
	msgbox TrainerSchoolSign_Text_0
# 9 "data/maps/Route1N/scripts.pory"
	release
	end


TrainerSchoolSign_Text_0:
# 5 "data/maps/Route1N/scripts.pory"
	.string "Let's learn and grow.\n"
	.string "Let's grow and train.\l"
	.string "Unsullied, enjoyable, and academic.\l"
	.string "Everyone starts at the beginning!$"
